"""empty message

Revision ID: 01301d1e7b10
Revises: 1e54f4d438b4
Create Date: 2020-05-05 21:10:31.857816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01301d1e7b10'
down_revision = '1e54f4d438b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
