"""empty message

Revision ID: 51787b94b87d
Revises: af5e8a43ca8f
Create Date: 2020-05-05 22:58:32.982156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51787b94b87d'
down_revision = 'af5e8a43ca8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
